services:
  dashboard:
    image: softvence/dtc6464_web:latest
    container_name: dtc6464_web
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL_DEV: https://api.datatechcon.com/api/v1
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dtc

networks:
  dtc:
    driver: bridge
